# Generated by Django 3.0.7 on 2020-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number2',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
