# Generated by Django 3.0.7 on 2020-06-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Username',
        ),
    ]
